# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('numTelefono', models.IntegerField()),
                ('fechaNacimiento', models.DateTimeField()),
                ('colorFavorito', models.CharField(max_length=150)),
                ('favoriteTags', models.CharField(max_length=200)),
                ('edad', models.PositiveIntegerField(blank=True)),
                ('calificacion', models.PositiveIntegerField(blank=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
            ],
        ),
    ]
